version: 2

workflows:
  version: 2
  ci:
    jobs:
      - py37
      - py36

jobs:
  py37: &job-template
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e .[testing]
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
  py36:
    <<: *job-template
    docker:
      - image: circleci/python:3.6
